#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Fusion Lab Marketplace: the 6 handoff steps that need accounts /
# credentials only the human can provide. See ROADMAP.md → "Хендофф".
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Resolve the repo root regardless of where this script is invoked from
# (it lives in scripts/, one level below the repo root).
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RAILWAY_API_URL=""

banner "Fusion Lab Marketplace — деплой і хендофф"

# ── Stage 1: Docker + first Prisma migration ───────────────────────────────
stage "Docker Desktop — Postgres/Redis локально + перша міграція"
say "Піднімаємо Postgres+Redis локально (docker-compose.yml вже в репо) і"
say "застосовуємо першу Prisma-міграцію схеми."

if ! command -v docker >/dev/null 2>&1; then
  step "Docker не знайдено — встановіть Docker Desktop."
  open_url "https://www.docker.com/products/docker-desktop/"
  pause "Встановіть і запустіть Docker Desktop, тоді натисніть Enter"
fi

until docker info >/dev/null 2>&1; do
  warn "Docker ще не відповідає (не запущений або ще стартує)."
  pause "Запустіть Docker Desktop і натисніть Enter, щоб перевірити знову"
done
note "Docker працює."

cd "$REPO_ROOT"
docker compose up -d
step "Чекаю, поки Postgres прийме з'єднання..."
for _ in $(seq 1 30); do
  docker compose exec -T postgres pg_isready -U fusionlab >/dev/null 2>&1 && break
  sleep 1
done
note "Postgres (5432) і Redis (6379) підняті."

cd "$REPO_ROOT/apps/api"
if [[ ! -f .env ]]; then
  printf 'DATABASE_URL="postgresql://fusionlab:fusionlab@localhost:5432/fusionlab"\n' > .env
  note "Створено apps/api/.env з локальним DATABASE_URL."
fi

if [[ -d prisma/migrations ]] && [[ -n "$(ls -A prisma/migrations 2>/dev/null)" ]]; then
  note "Міграції вже є в prisma/migrations — пропускаю."
else
  npx prisma migrate dev --name init
  note "Перша міграція застосована."
fi
cd "$REPO_ROOT"

# ── Stage 2: Firebase service account + client config ──────────────────────
stage "Firebase — службовий акаунт (сервер) + публічний конфіг (клієнт)"
say "Спершу серверні креденшли (приватні, для NestJS), потім клієнтські"
say "(публічні, безпечні для фронтенду)."

open_url "https://console.firebase.google.com/project/fusionlab-acc2d/settings/serviceaccounts/adminsdk"
step "Натисніть 'Generate new private key' → підтвердіть — завантажиться JSON."
step "Відкрийте цей JSON-файл у текстовому редакторі."
pause "Натисніть Enter, коли файл відкрито"

ENV_FILE="$REPO_ROOT/apps/api/.env"
ask FIREBASE_PROJECT_ID "Значення поля \"project_id\" (типово fusionlab-acc2d):"
ask FIREBASE_CLIENT_EMAIL "Значення поля \"client_email\":"
step "Скопіюйте значення поля \"private_key\" ЦІЛИКОМ як один рядок"
step "(з літеральними \\n усередині — не розбивайте на кілька рядків)."
ask_secret FIREBASE_PRIVATE_KEY "Вставте private_key:"
write_env FIREBASE_PROJECT_ID "$FIREBASE_PROJECT_ID"
write_env FIREBASE_CLIENT_EMAIL "$FIREBASE_CLIENT_EMAIL"
write_env FIREBASE_PRIVATE_KEY "$FIREBASE_PRIVATE_KEY"

say ""
say "Тепер публічний клієнтський конфіг."
open_url "https://console.firebase.google.com/project/fusionlab-acc2d/settings/general"
step "'Your apps' → Web app → 'SDK setup and configuration' → 'Config'."

ENV_FILE="$REPO_ROOT/apps/web/.env.local"
ask NEXT_PUBLIC_FIREBASE_API_KEY "Значення apiKey:"
write_env NEXT_PUBLIC_FIREBASE_API_KEY "$NEXT_PUBLIC_FIREBASE_API_KEY"
write_env NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN "fusionlab-acc2d.firebaseapp.com"
write_env NEXT_PUBLIC_FIREBASE_PROJECT_ID "fusionlab-acc2d"

# ── Stage 3: GitHub repo + push ─────────────────────────────────────────────
stage "GitHub — репозиторій і перший push"
cd "$REPO_ROOT"

if git remote get-url origin >/dev/null 2>&1; then
  note "git remote 'origin' вже налаштований — пропускаю: $(git remote get-url origin)"
else
  ask GITHUB_REPO_NAME "Назва нового репозиторію [fusion-lab-marketplace]:"
  GITHUB_REPO_NAME="${GITHUB_REPO_NAME:-fusion-lab-marketplace}"
  note "Публічний — щоб рецензент вакансії міг переглянути код без запрошення."

  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    step "Знайдено GitHub CLI — створюю репозиторій і одразу пушу."
    gh repo create "$GITHUB_REPO_NAME" --public --source=. --remote=origin --push
  else
    open_url "https://github.com/new"
    step "Ім'я: $GITHUB_REPO_NAME. Public. НЕ додавайте README/.gitignore/license"
    step "(репозиторій уже має історію — README/.gitignore тут спричинить конфлікт)."
    step "Створіть, скопіюйте URL репозиторію (HTTPS)."
    ask GITHUB_REPO_URL "Вставте URL репозиторію:"
    git remote add origin "$GITHUB_REPO_URL"
    git push -u origin master
  fi
fi
note "git remote:"
git remote -v

# ── Stage 4: Vercel ──────────────────────────────────────────────────────────
stage "Vercel — деплой apps/web"
say "Next.js-фронтенд деплоїться напряму з GitHub-репозиторію."
open_url "https://vercel.com/new"
step "Import Git Repository → оберіть щойно запушений репозиторій."
step "Configure Project → Root Directory → Edit → apps/web."
step "Environment Variables — ті самі значення, що щойно записані в"
step "apps/web/.env.local: NEXT_PUBLIC_FIREBASE_API_KEY,"
step "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN, NEXT_PUBLIC_FIREBASE_PROJECT_ID."
step "NEXT_PUBLIC_API_URL — поки заглушка (напр. http://localhost:3001)."
note "Оновимо на реальний в останній стадії, коли буде відомий Railway/DNS-URL."
step "Deploy."
pause "Натисніть Enter, коли деплой Vercel завершено (є Production URL)"

# ── Stage 5: Railway ─────────────────────────────────────────────────────────
stage "Railway — деплой apps/api + Postgres + Redis"
say "Бекенд деплоїться через apps/api/Dockerfile, білд-контекст — корінь монорепо."
open_url "https://railway.app/new"
step "New Project → Deploy from GitHub repo → той самий репозиторій."
step "У сервісі: Settings → Dockerfile Path → apps/api/Dockerfile"
step "(Root Directory лишити порожнім — Dockerfile сам білдиться з кореня)."
step "New → Database → Add PostgreSQL (у тому ж проєкті)."
step "New → Database → Add Redis (у тому ж проєкті)."
step "У Variables сервісу apps/api додайте (Railway дозволяє посилатись"
step "на інший сервіс проєкту):"
note "  DATABASE_URL = \${{Postgres.DATABASE_URL}}"
note "  REDIS_URL    = \${{Redis.REDIS_URL}}"
step "Додайте також 3 Firebase-змінні — ті самі значення, що в apps/api/.env:"
note "  FIREBASE_PROJECT_ID, FIREBASE_CLIENT_EMAIL, FIREBASE_PRIVATE_KEY"
step "Deploy. Тоді Settings → Networking → Generate Domain — публічний URL."
ask RAILWAY_API_URL "Вставте отриманий URL (напр. https://xxxx.up.railway.app):"
note "Знадобиться в наступній стадії для NEXT_PUBLIC_API_URL."

# ── Stage 6: DNS + finalize NEXT_PUBLIC_API_URL ─────────────────────────────
stage "DNS для fusionlab.in.ua + фінальний NEXT_PUBLIC_API_URL"
say "Прив'язуємо власний домен і оновлюємо URL API у фронтенді."

open_url "https://vercel.com/dashboard"
step "Ваш проєкт → Settings → Domains → Add → fusionlab.in.ua."
step "Vercel покаже потрібні A/CNAME записи."

open_url "https://railway.app/dashboard"
step "Сервіс apps/api → Settings → Networking → Custom Domain →"
step "напр. api.fusionlab.in.ua. Railway покаже CNAME-запис."

step "Додайте обидва записи в DNS-панелі реєстратора fusionlab.in.ua."
warn "DNS може поширюватись до кількох годин — не обов'язково чекати зараз."

ENV_FILE="$REPO_ROOT/apps/web/.env.local"
API_URL_DEFAULT="${RAILWAY_API_URL:-https://api.fusionlab.in.ua}"
ask NEXT_PUBLIC_API_URL "Фінальний URL API [$API_URL_DEFAULT]:"
NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL:-$API_URL_DEFAULT}"
write_env NEXT_PUBLIC_API_URL "$NEXT_PUBLIC_API_URL"

warn "Оновіть NEXT_PUBLIC_API_URL і в самому Vercel-проєкті (Settings →"
warn "Environment Variables) і зробіть Redeploy — Vercel не читає локальний"
warn "apps/web/.env.local."

if command -v nslookup >/dev/null 2>&1; then
  note "DNS-перевірка (може ще не встигнути поширитись):"
  nslookup fusionlab.in.ua 2>&1 | tail -5 || true
fi

finish
